print(True)
print(False)
print()
print(10 == 100)
print(10 != 100)
print(10 < 100)
print(10 > 100)
print(10 <= 100)
print(10 >= 100)
print()
print("가방" == "가방")
print("가방" != "하마")
print("가방" < "하마")
print("가방" > "하마")
print()
x = 25
print(10 < x < 30)
print(40 < x < 60)
print()
print(not True)
print(not False)
print()
x = 10
under_20 = x < 20
print("under_20: ", under_20)
print("not under_20: ", not under_20)
print()
print()
print(True and True)
print(True and False)
print(False and True)
print(False and False)
print()
print(True or True)
print(True or False)
print(False or True)
print(False or False)
print()